-- =============================================================
-- Alana Pirangi | Psicanalista — Schema do banco de dados
-- Recriação completa no novo projeto Supabase
-- =============================================================

-- -------------------------------------------------------------
-- 1. TABELAS
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.posts (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug      text        NOT NULL UNIQUE,
  title     text        NOT NULL,
  tag       text        NOT NULL DEFAULT '',
  category  text        NOT NULL DEFAULT 'geral',
  image     text        NOT NULL DEFAULT '',
  excerpt   text        NOT NULL DEFAULT '',
  content   text        NOT NULL DEFAULT '',
  date      date        NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS posts_slug_idx     ON public.posts (slug);
CREATE INDEX IF NOT EXISTS posts_date_idx     ON public.posts (date DESC);
CREATE INDEX IF NOT EXISTS posts_category_idx ON public.posts (category);

CREATE TABLE IF NOT EXISTS public.categories (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.comments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_slug  text        NOT NULL,
  post_title text        NOT NULL DEFAULT '',
  author     text        NOT NULL,
  content    text        NOT NULL,
  date       date        NOT NULL DEFAULT CURRENT_DATE,
  approved   boolean     NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS comments_post_slug_idx ON public.comments (post_slug);
CREATE INDEX IF NOT EXISTS comments_approved_idx  ON public.comments (approved);

CREATE TABLE IF NOT EXISTS public.media (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text        NOT NULL,
  data_url   text        NOT NULL,
  type       text        NOT NULL DEFAULT '',
  size       bigint      NOT NULL DEFAULT 0,
  date       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS media_date_idx ON public.media (date DESC);

CREATE TABLE IF NOT EXISTS public.settings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        text NOT NULL UNIQUE,
  value      jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------
-- 2. ROW LEVEL SECURITY
--    O front-end (public/assets/js/data.js) usa a publishable key
--    para ler E escrever em todas as tabelas, então as políticas
--    liberam anon/authenticated nos 4 verbos.
-- -------------------------------------------------------------

ALTER TABLE public.posts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings   ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['posts','categories','comments','media','settings'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "anon_all" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_all" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "anon_all" ON public.%I FOR ALL TO anon USING (true) WITH CHECK (true)', t);
    EXECUTE format(
      'CREATE POLICY "auth_all" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

-- -------------------------------------------------------------
-- 3. STORAGE — bucket público "media"
--    usado por DB.uploadMedia() (POST em /storage/v1/object/media/...)
-- -------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('media', 'media', true, 52428800, NULL)
ON CONFLICT (id) DO UPDATE
  SET public             = EXCLUDED.public,
      file_size_limit   = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "anon_storage_all" ON storage.objects;

CREATE POLICY "anon_storage_all" ON storage.objects
  FOR ALL TO anon
  USING (bucket_id = 'media')
  WITH CHECK (bucket_id = 'media');

DROP POLICY IF EXISTS "anon_storage_read" ON storage.objects;

CREATE POLICY "anon_storage_read" ON storage.objects
  FOR SELECT TO anon
  USING (bucket_id = 'media');

-- -------------------------------------------------------------
-- 4. SEED — dados iniciais
--    (o front-end também roda DB.init(), mas populamos aqui para
--     que o banco já fique pronto)
-- -------------------------------------------------------------

INSERT INTO public.categories (name) VALUES
  ('Teoria Lacaniana'),
  ('Clínica'),
  ('Cultura'),
  ('Sonhos'),
  ('Sintoma'),
  ('Desejo')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.settings (key, value) VALUES
  ('site_config', '{
    "siteTitle": "Alana Pirangi | Psicanalista",
    "siteDescription": "Psicanálise de orientação lacaniana — o inconsciente estruturado como linguagem, o desejo como ética.",
    "keywords": "psicanálise, lacan, freud, psicanalista, inconsciente",
    "email": "contato@alanapirangi.com.br",
    "city": "Taguatinga - Brasília - DF",
    "socialLinks": []
  }'::jsonb)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.posts (slug, title, tag, category, image, excerpt, content, date) VALUES
  (
    'o-inconsciente-estruturado',
    'O Inconsciente Estruturado como Linguagem',
    'Teoria Lacaniana',
    'teoria',
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80',
    'Uma introdução ao conceito fundamental de Jacques Lacan: o inconsciente não é um reservatório de instintos, mas um saber que se articula como uma linguagem.',
    '<p>Lacan parte do ensino de Saussure para propor que o inconsciente é estruturado como uma linguagem. Isso significa que os processos inconscientes — condensação e deslocamento — são equivalentes à metáfora e à metonímia.</p><p>O sintoma, o sonho, o ato falhado e o chiste são formações do inconsciente que obedecem a uma lógica significante. Cabe ao analista escutar, não o sentido oculto, mas a cadeia de significantes que se repete na fala do analisando.</p>',
    '2026-06-10'
  ),
  (
    'desejo-e-falta',
    'Desejo e Falta: A Ética Lacaniana',
    'Teoria Lacaniana',
    'teoria',
    'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&q=80',
    'O desejo não é a busca por um objeto, mas aquilo que se sustenta na falta. Uma reflexão sobre a ética do desejo na psicanálise.',
    '<p>Para Lacan, o desejo é o desejo do Outro. Não se trata de um desejo que já nos pertenceria, mas de um desejo constituído na linguagem e na relação com o Outro.</p><p>A falta-a-ser (manque-à-être) é estrutural: o sujeito é marcado por uma perda fundamental que o constitui como desejante. A psicanálise não promete preencher essa falta, mas ensinar o sujeito a desejar apesar dela — ou através dela.</p>',
    '2026-06-10'
  ),
  (
    'o-sinthoma',
    'Do Sintoma ao Sinthoma',
    'Clínica',
    'clinica',
    'https://images.unsplash.com/photo-1493836512294-46a9d6985c0a?w=800&q=80',
    'O percurso do sintoma na obra de Lacan: de formação do inconsciente a invenção singular que amarra os três registros.',
    '<p>No início de seu ensino, Lacan define o sintoma como uma formação do inconsciente — uma metáfora que retorna como mensagem a ser decifrada.</p><p>Ao final de sua obra, o sintoma torna-se sinthoma: uma invenção singular que amarra os registros Real, Simbólico e Imaginário. Não se trata mais de decifrar, mas de identificar-se com o sintoma — fazer dele um modo de gozo que sustenta a vida.</p>',
    '2026-06-10'
  )
ON CONFLICT (slug) DO NOTHING;
